name: django_training

services:
  postgresql:
    container_name: postgres
    # https://hub.docker.com/_/postgres
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
        # Dev env values (insecure)
        POSTGRES_PASSWORD: 'secret'
        POSTGRES_USER: 'djangouser' 
        POSTGRES_DB: 'djangotraining'
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
  adminer:
    container_name: adminer
    # https://hub.docker.com/_/adminer
    image: adminer
    environment:
        ADMINER_DESIGN: 'dracula'
        ADMINER_DEFAULT_SERVER: postgresql
    ports:
      - "8080:8080"

volumes:
  postgres_volume:
      driver: local
      driver_opts:
          type: none
          device: ./db
          o: bind

