services:
  database:
    image: "postgres:18-alpine"
    container_name: leetcode_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev}
      POSTGRES_DB: ${DB_DATABASE:-dev}
    volumes:
      # Any .sql file here is executed automatically on first startup!
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # Comment out pgdata if you want a clean database every restart
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

# Run with:
#     docker compose up -d
# Tear down with:
#     docker compose down -v
#       (-v removes stored volume data).
# Connecting via Terminal inside Docker:
#     docker exec -it pg-test psql -U postgres

# Running
# source .env && watchexec -e sql "docker compose exec -T database psql -U $DB_USER -d $DB_DATABASE < solution.sql"

# Config
# docker compose --env-file .env config

# TUI:
# harlequin -a postgres "postgres://dev:dev@localhost:5432/dev"
