# Generated by Django 4.2.16 on 2024-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_pro_tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tip',
            name='last_activity',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
