# Generated by Django 4.2.16 on 2024-11-05 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('life_pro_tips', '0002_tip_downvotes_tip_last_activity_tip_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='upvotes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('U', 'Upvote'), ('D', 'Downvote')], max_length=1)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life_pro_tips.tip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tip')},
            },
        ),
        migrations.AddField(
            model_name='tip',
            name='votes',
            field=models.ManyToManyField(related_name='votes', through='life_pro_tips.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
